# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_remove_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_hash',
            field=models.CharField(default='abcdefghijklmnopqrstuvwxyz1234567890', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
