# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-20 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0004_users_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='logged_in',
        ),
    ]
